name: Sphinx Build

on:
  push:
    branches:
      - main  # Change this to your main branch name
      - docs-workflow-file
permissions:
  contents: write
jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r docsrc/requirements.txt  # Assuming your Sphinx dependencies are listed in requirements.txt

    - name: Build docs
      run: |
        sphinx-build -b html docsrc docs

    - name: Deploy Docs
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs


